name: Odoo Lint and Deploy

on:
  push:
    branches:
      - main  # only deploy on main branch

jobs:
  lint:
    name: Lint Odoo Module with pylint-odoo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pylint-odoo
        run: |
          pip install pylint pylint-odoo

      - name: Run pylint-odoo
        run: |
          pylint --load-plugins=pylint_odoo your_module_dir/
  
  deploy:
    name: Deploy to Odoo Server
    runs-on: ubuntu-latest
    needs: lint
    if: success() && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy with rsync
        run: |
          rsync -avz --delete ./your_module_dir/ user@your-server:/opt/odoo/custom_addons/your_module_dir/
